name: Check Certificate Status
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Check certs
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl certs setup bhrefs.com --app backlink-finder
          echo "---www---"
          flyctl certs setup www.bhrefs.com --app backlink-finder
