name: Check Certificate Status
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Reset and re-add cert
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl certs remove bhrefs.com --app backlink-finder -y || true
          sleep 5
          flyctl certs add bhrefs.com --app backlink-finder
          sleep 10
          flyctl certs check bhrefs.com --app backlink-finder
